#!/bin/sh
#
# Starts MycroftOS-WiFiSetup.
#

start() {
	printf "Starting MycroftOS-WiFiSetup: "
	umask 077
	bash /usr/lib/node-modules/MycroftOS-WiFiSetup/run.sh
	echo "OK"
}
stop() {
	printf "Stopping MycroftOS-WiFiSetup: "
	killall run.sh
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

